import type {Metadata} from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Niles' Next.js 26.01.24",
  description: "Generated by my phone",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="bg-background dark container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4 font-sans antialiased">
        
        <main className="py-8">{children}</main>
      </body>
    </html>
  );
}
